[versions]
# libraries
junit = "4.13.2"
# plugins
intelliJPlatform = "2.0.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }